'use strict';
/* ===== Режим разработчика (включается в Настройках или ?dev=1, панель — F2) ===== */
UI.toggleDev = function () {
  let box = $('#dev');
  if (box) { box.remove(); return; }
  box = el('div', 'devbox'); box.id = 'dev'; document.body.appendChild(box);
  const P = () => G.P, prof = () => G.prof;
  const row = (title, ...nodes) => { const r = el('div', 'dvrow'); if (title) r.appendChild(el('b', '', title)); nodes.forEach(n => r.appendChild(n)); box.appendChild(r); return r; };
  const btn = (t, fn) => { const b = el('button', 'dvb', t); b.onclick = () => { fn(); UI.dirty = true; }; return b; };
  const tog = (t, key) => { const b = el('button', 'dvb' + (G_DEV[key] ? ' on' : ''), t); b.onclick = () => { G_DEV[key] = !G_DEV[key]; b.classList.toggle('on', G_DEV[key]); }; return b; };
  const sel = (opts, cb) => { const s = el('select'); opts.forEach(([v, n]) => { const o = el('option', '', n); o.value = v; s.appendChild(o); }); s._cb = cb; return s; };
  box.innerHTML = '<div class="dvh">🛠 Режим разработчика <i>(F2 — закрыть)</i></div>';
  row('Читы', tog('Бессмертие', 'god'), tog('Убийство с 1 удара', 'onehit'), tog('Скорость ×2.5', 'fast'), tog('Полёт', 'fly'));
  row('Герой', btn('❤ Полное здоровье', () => { P().hp = P().maxHp; P().res = P().maxRes; }), btn('+1 ур.', () => { const p = prof(); if (p.lvl < MAX_LEVEL) { p.lvl++; p.sp++; p.xp = 0; recalc(); } }), btn('Ур. 20', () => { const p = prof(); p.lvl = MAX_LEVEL; p.sp += 19; recalc(); P().hp = P().maxHp; }), btn('+5 очков умений', () => { prof().sp += 5; }), btn('+10000 💰', () => addGold(10000)));
  row('Набор', btn('Материалы и еда', () => { ['iron_ore', 'iron_ingot', 'moonroot', 'gem', 'meat', 'wolf_pelt', 'troll_hide', 'spider_silk', 'ectoplasm', 'bear_claw', 'feather', 'slime_gel', 'bone'].forEach(i => addItem(i, 10, true)); Object.keys(CROPS).forEach(k => { addItem('crop_' + k, 10, true); addItem('seed_' + k, 10, true); }); addItem('rod', 1, true); ['hp_2', 'rs_2', 'lure', 'treat'].forEach(i => addItem(i, 10, true)); toast('Выдан набор', 'good'); }), btn('Всё оружие/броня класса (T1–T4)', () => { const C = CLASSES[prof().cls]; for (let t = 0; t < 4; t++) { addItem(`w_${C.weapon}_${t}`, 1, true); C.armor.forEach(a => ['body', 'head', 'boots'].forEach(s => addItem(`a_${a}_${s}_${t}`, 1, true))); } }));
  const iid = sel(Object.keys(ITEMS).map(k => [k, `${ITEMS[k].name}`]), null); const ip = row('Предмет', iid, btn('+1', () => addItem(iid.value, 1)), btn('+10', () => addItem(iid.value, 10)));
  const tp = sel(Object.keys(LOCS).map(k => [k, LOCS[k].name]), null); row('Телепорт', tp, btn('Идти', () => { const l = LOCS[tp.value]; let x = l.x, y = l.y; if (y < OW_H) { const q = G.world.nearestWalk(Math.round(x), Math.round(y)); if (q) { x = q[0]; y = q[1]; } } else { const q = G.world.nearestWalk(Math.round(x - 12), Math.round(y + 1)); if (q) { x = q[0]; y = q[1]; } } P().x = (x + 0.5) * TS; P().y = (y + 1) * TS - 6; if (G.petEnt) { G.petEnt.x = P().x; G.petEnt.y = P().y; } G.cam.x = P().x - innerWidth / G.cam.zoom / 2; G.cam.y = P().y - innerHeight / G.cam.zoom / 2; }));
  row('Время', ...[6, 12, 18, 22, 0].map(h => btn(h + ':00', () => { const d = gt(); G.min = d.absDay * 1440 + h * 60 + (h * 60 <= d.hour * 60 + d.minute ? 1440 : 0); updateEvents(); })), btn('+1 день', () => { G.min += 1440; for (let i = 0; i < 1; i++) onMinute(); }));
  const es = sel(EVENTS.map(e => [e.id, e.icon + ' ' + e.name]), null); row('Событие', es, btn('Начать', () => { const ev = EVENTS.find(e => e.id === es.value); const d = gt(); for (let i = 0; i < 400; i++) { const day = d.absDay + i, dd = calc(day * 1440 + 720); if (ev.when(dd)) { G.min = day * 1440 + ev.from * 60 + 1; break; } } updateEvents(); }));
  const ms = sel(Object.keys(MON).map(k => [k, MON[k].name]), null); const ml = el('input'); ml.type = 'number'; ml.value = 5; ml.style.width = '50px';
  row('Монстр', ms, ml, btn('Создать у курсора', () => { const m = spawnEventMon(ms.value, Math.floor(G.mouse.wx / TS), Math.floor(G.mouse.wy / TS), +ml.value || 5, 'dev'); m.state = 'idle'; })), row('', btn('Убить всех рядом', () => G.mons.forEach(m => { if (!m.dead && !m.hidden && Math.hypot(m.x - P().x, m.y - P().y) < 600) damageMon(m, 1e9, { dot: true }); })), btn('Открыть карту', () => { G.revealed.fill(1); G.mapDirty = true; }), btn('Пропустить обучение', () => { prof().flags.tut = 6; }));
  row('Задания', btn('Завершить активные', () => { for (const id in prof().quests) { const q = prof().quests[id]; if (q.state === 'active') { QUESTS[id].obj.forEach((o, i) => { q.prog[i] = objNeed(o); if (o.t === 'collect') addItem(o.id, o.n, true); }); q.ready = true; } } questRecheck(); }), btn('Сбросить боссов', () => { prof().defeated = []; spawnMonsters(); }), btn('Все проекты города', () => { Object.keys(PROJECTS).forEach(k => prof().projects[k] = true); recalc(); }));
  const ts = el('input'); ts.type = 'range'; ts.min = 1; ts.max = 60; ts.value = G.timeScale; ts.oninput = () => { G.timeScale = +ts.value; }; row('Время: мин/с', ts);
};
